### PR TITLE
Basic search index

### PR DESCRIPTION
**Pull request by Th1nkK1D**
Implementing basic search function with index file

# Prototype 1

## Implementation
1. Implement content index builder which
-- Use `js-yaml` to read content yaml
-- Reshape to object as discussed in #11 
-- Write index.yaml back to contents folders

2. Index builder will be triggered by Gatsby node API `onPreInit()` during `gatsby build`
3. Index can be query using GraphQL query (easy to use in search component). For example:
```graphql
query MyQuery {
  allIndexYaml() {
    nodes {
      type
      url
      q
    }
  }
}
```

## Result and Discussion
- Index yaml file containing party, people votelog has size of 106kb (Is it acceptable?)
- Index file optimization can be added ex. using index instead of full string or other data structure
- An ability to quary with GraphQL is interesting to me :)
- **I know this is not the best way but is it acceptable according to the project situation?**

### CODE REVIEW

**Comment by rapee** [comment]
Looks good to me. Can you change built index file name to something like `/search_index.yaml`? 

`index.yaml` is too ambiguous I think.

**Comment by Th1nkK1D** [comment]
> Looks good to me. Can you change built index file name to something like `/search_index.yaml`?
> 
> `index.yaml` is too ambiguous I think.

Sure I can! Also want to ask if you want to include any other data source? And should I create a simple search box component? Since we can only bind GraphQL to a component and regex search is not implemented yet.

**Comment by Th1nkK1D** [comment]
Gonna go for vacation for a week. I will set it to ready for review na krub :)

**Comment by rapee** [comment]
- Current set of data source is fine. We'll add in another occasion.
- Search box component is #10
- I think there're 2 ways to do search: 1. Bind search index GraphQL to a component or 2. Expose search index as public file and let frontend consumes it.

**Pull request merged**
