### PR TITLE
Display contributor list by fetching from GitHub API

### PR DESCRIPTION
**Pull request by mixth**
For #50.

# Changes
- [x] Fetching contributor list of this repo using GitHub REST API v3
- [x] Populating the list in build-time
- [x] Applying the list to About page
- [ ] More styling?

# Screenshot
Screen Shot 2019-11-02 at 10 04 37 PM

### CODE REVIEW

**Comment by p16i** [comment]
Oh nice! imho, the style can be updated later.

**Comment by rapee** [comment]
@mixth Great work!

Note that other contributors (e.g. designers) will be added by hand.

**Comment by mixth** [comment]
If the current style is good enough, this pull request is ready to be merged. 😃

**Comment by p16i** [comment]
@rapee, I agree with @mixth. We can merge this PR because (i guess) there'll be another iteration adjusting the style. The current version is quite good already.

**Comment by rapee** [comment]
@mixth @heytitle Merged!

**Pull request merged**
