### PR TITLE
add voterecord to Votelog Detail View section #75

### PR DESCRIPTION
**Pull request by thasarito**
#75 

I create vote record section first. I will add waffle chart later when waffle chart on index page have drop down list.

### CODE REVIEW

**Comment by rapee** [comment]
Thanks! @thasarito 

So I'll keep this issue open until you finish with the waffle.

Do you also plan to revise the design?

**Comment by thasarito** [comment]
@rapee 

Which part of the design do you want me to revise?

**Comment by rapee** [comment]
Dark background color, link color, section separators, and other positioning @thasarito

**Comment by thasarito** [comment]
Yes, I will do it. @rapee

**Pull request merged**
